### ISSUE TITLE
Random Firefly Crash on 1.1.6 (1.19.2)

### ISSUE THREAD

**Issue by tutter05** [Ineffa/Wondrous-Wilds#12]
Crashes happen seemingly random
[crash-2023-05-28_15.53.23-server.txt](https://github.com/Ineffa/Wondrous-Wilds/files/11584836/crash-2023-05-28_15.53.23-server.txt)

**Comment by enzomtpYT** [comment]
Same here :
```[17:12:39] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.lang.ThreadLocal.get()" is null
	at net.minecraft.class_1309.handler$zcl000$porting_lib_base$port_lib$spawnDropsTAIL(class_1309.java:5201) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_16080(class_1309.java:1397) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_6078(class_1309.java:1348) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5643(class_1309.java:1204) ~[server-intermediary.jar:?]
	at net.minecraft.class_1429.method_5643(class_1429.java:80) ~[server-intermediary.jar:?]
	at com.ineffa.wondrouswilds.entities.FireflyEntity.method_5643(FireflyEntity.java:158) ~[wondrouswilds-1.19.2-1.1.6.jar:?]
	at net.minecraft.class_1297.method_5730(class_1297.java:577) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5670(class_1297.java:527) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5670(class_1309.java:349) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.method_5670(class_1308.java:286) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5773(class_1297.java:469) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2346) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:353) ~[server-intermediary.jar:?]
	at com.ineffa.wondrouswilds.entities.FireflyEntity.method_5773(FireflyEntity.java:146) ~[wondrouswilds-1.19.2-1.1.6.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:712) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:466) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:371) ~[server-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:339) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[server-intermediary.jar:?]
	... 5 more```

**Comment by NeffaDev** [comment]
This crash appears to be coming from a library called Porting Lib through mixins.

Do you have any more details on when this occurs in-game? Also, what mods are you using that depend on Porting Lib?

**Comment by enzomtpYT** [comment]
For me the last time it happenend was when a creeper blew up a firefly (im using "Curiosities: The Sequel" modpack)

**Comment by NeffaDev** [comment]
This probably isn't an issue with Porting Lib itself but rather a mod that is using it. I don't know what mod could be the culprit though because said mod seems to have JIJ'd the library, on top of the crash already being difficult to reproduce. 😕
